-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 22:55:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql7283170
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql7283170
-- -----------------------------------------------------
USE `sql7283170` ;

-- -----------------------------------------------------
-- Table `sql7283170`.`Group`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sql7283170`.`Group` (
  `ID_group` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`ID_group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7283170`.`Student`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sql7283170`.`Student` (
  `ID_student` VARCHAR(9) NOT NULL,
  `Gender` VARCHAR(1) NOT NULL,
  `FirstName` VARCHAR(64) NOT NULL,
  `LastName` VARCHAR(64) NOT NULL,
  `Birthday` DATE NOT NULL,
  `Bac` VARCHAR(16) NULL DEFAULT NULL,
  `BacYear` INT(11) NULL DEFAULT NULL,
  `BacGrade` VARCHAR(2) NULL DEFAULT NULL,
  `Degree` VARCHAR(16) NULL DEFAULT NULL,
  `DegreeYear` INT(11) NULL DEFAULT NULL,
  `DegreeCity` VARCHAR(64) NULL DEFAULT NULL,
  `RegistrationYear` INT(11) NULL DEFAULT NULL,
  `EmailPro` VARCHAR(64) NULL DEFAULT NULL,
  `EmailPer` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_student`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7283170`.`IncludedStudent`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sql7283170`.`IncludedStudent` (
  `ID_group` INT NOT NULL,
  `ID_student` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_group`, `ID_student`),
  CONSTRAINT `IncludedStudent_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `sql7283170`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IncludedStudent_Student_ID_student_fk`
    FOREIGN KEY (`ID_student`)
    REFERENCES `sql7283170`.`Student` (`ID_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `sql7283170`.`ExcludedStudent`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sql7283170`.`ExcludedStudent` (
  `ID_student` VARCHAR(9) NOT NULL,
  `ID_group` INT NOT NULL,
  PRIMARY KEY (`ID_student`, `ID_group`),
  CONSTRAINT `ExcludedStudent_Student_ID_student_fk`
    FOREIGN KEY (`ID_student`)
    REFERENCES `sql7283170`.`Student` (`ID_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ExcludedStudent_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `sql7283170`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `sql7283170`.`IncludedGroup`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `sql7283170`.`IncludedGroup` (
  `ID_group` INT NOT NULL,
  `ID_group_child` INT NOT NULL,
  PRIMARY KEY (`ID_group`, `ID_group_child`),
  CONSTRAINT `IncludedGroup_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `sql7283170`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IncludedGroup_Group_ID_group_child_fk`
    FOREIGN KEY (`ID_group_child`)
    REFERENCES `sql7283170`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
