-- MySQL Script generated by MySQL Workbench
-- Wed Mar 13 22:55:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetJEE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetJEE
-- -----------------------------------------------------
USE `projetJEE` ;

-- -----------------------------------------------------
-- Table `projetJEE`.`Group`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`Group` (
  `ID_group` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL UNIQUE,
  `ID_owner` INT NOT NULL,
  `creationDate` DATE NOT NULL,
  PRIMARY KEY (`ID_group`),
  CONSTRAINT `Group_User_ID_owner_fk`
    FOREIGN KEY (`ID_owner`)
    REFERENCES `projetJEE`.`User` (`ID_user`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `projetJEE`.`User`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`User` (
  `ID_user` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(64) NOT NULL UNIQUE,
  `pwdHash` VARCHAR(256) NOT NULL,
  `question` VARCHAR(256) NOT NULL,
  `answerHash` VARCHAR(256) NOT NULL,
  `rights` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetJEE`.`Student`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`Student` (
  `ID_student` VARCHAR(9) NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `firstname` VARCHAR(64) NOT NULL,
  `lastname` VARCHAR(64) NOT NULL,
  `birthday` DATE NOT NULL,
  `bac` VARCHAR(16) NULL DEFAULT NULL,
  `bacYear` INT(11) NULL DEFAULT NULL,
  `bacGrade` VARCHAR(2) NULL DEFAULT NULL,
  `degree` VARCHAR(16) NULL DEFAULT NULL,
  `degreeYear` INT(11) NULL DEFAULT NULL,
  `degreeCity` VARCHAR(64) NULL DEFAULT NULL,
  `registrationYear` INT(11) NULL DEFAULT NULL,
  `emailPro` VARCHAR(64) NULL DEFAULT NULL,
  `emailPer` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_student`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetJEE`.`IncludedStudent`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`IncludedStudent` (
  `ID_group` INT NOT NULL,
  `ID_student` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`ID_group`, `ID_student`),
  CONSTRAINT `IncludedStudent_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `projetJEE`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IncludedStudent_Student_ID_student_fk`
    FOREIGN KEY (`ID_student`)
    REFERENCES `projetJEE`.`Student` (`ID_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `projetJEE`.`IncludedStudent`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`ExcludedStudent` (
  `ID_student` VARCHAR(9) NOT NULL,
  `ID_group` INT NOT NULL,
  PRIMARY KEY (`ID_student`, `ID_group`),
  CONSTRAINT `ExcludedStudent_Student_ID_student_fk`
    FOREIGN KEY (`ID_student`)
    REFERENCES `projetJEE`.`Student` (`ID_student`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ExcludedStudent_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `projetJEE`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

-- -----------------------------------------------------
-- Table `projetJEE`.`IncludedGroup`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetJEE`.`IncludedGroup` (
  `ID_group` INT NOT NULL,
  `ID_group_child` INT NOT NULL,
  PRIMARY KEY (`ID_group`, `ID_group_child`),
  CONSTRAINT `IncludedGroup_Group_ID_group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `projetJEE`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `IncludedGroup_Group_ID_group_child_fk`
    FOREIGN KEY (`ID_group_child`)
    REFERENCES `projetJEE`.`Group` (`ID_group`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
